name: DireParkour
version: ${version}
main: net.direskies.direparkour.Main
author: UltraGameCoder
description: Made by UltraGameCoder
api-version: 1.18

commands:
  parkour:
    description: The main command for the direskies parkour plugin.
    aliases:
      - pk

permissions:
  direparkour.admin:
    description: Required to configure DireParkour